### ISSUE TITLE
Not exporting appdata correctly until the builders are updated

### ISSUE THREAD

**Issue by nedrichards** [flathub/im.srain.Srain#1]
This needs to export a 128px icon for full visibility in software stores and the future flathub website.

**Comment by SilverRainZ** [comment]
Hello, how to export it? the 128px icon is available at `${PREFIX}/user/share/icons/hicolor/128x128/apps`.

**Comment by nedrichards** [comment]
It should be ${PREFIX}/share/icons/hicolor/128x128/apps/

**Comment by cpba** [comment]
I don't think that's what's causing it, flatpak-builder's output seems to find it just fine:

`Exporting share/icons/hicolor/128x128/apps/im.srain.Srain.png`

Also, after installing srain from flathub, the icon shows up in `/var/lib/flatpak/exports/share/icons/hicolor/128x128/apps/im.srain.Srain.png` as expected.

The only thing off I find about it is that it's 128x123 rather than being square, but I've been told that shouldn't break anything.

**Comment by TingPing** [comment]
Two bugs I believe: `<id>im.srain.Srain</id>` this was broken in flatpak, but fixed, don't know if builders have it yet?

`<launchable type="desktop-id">Srain.desktop</launchable>` rename-desktop-file might not pick that up (which would be a flatpak bug). Anyway just rename the data files upstream.

**Comment by nedrichards** [comment]
@TingPing I think Centos builders don't have the update, which I thought was just chergert's builder but seemingly yes, that's the issue I'm reporting.

**Comment by SilverRainZ** [comment]
What is the situation now?

**Comment by cpba** [comment]
My understanding was that the last commit would fix this but it didn't.

Srain still doesn't appear here:

https://flathub.org/apps/

Although it does show up in the beta site:

https://beta.flathub.org/apps/details/im.srain.Srain

**Comment by TingPing** [comment]
@cpba No the `id` needs to be changed, which is really a bug on *our* end.

Side note, please do not point the sources anywhere except upstream.

**Comment by cpba** [comment]
Oh good, then we'll just leave this one open until that's sorted.

> Side note, please do not point the sources anywhere except upstream.

Sorry about that, it was a bit embarrassing. I hope I didn't mess up anything on your end.

**Comment by nedrichards** [comment]
Further update from the flathub builder side. All hosts need to use at least version 0.7.5 of appstream-glib to correctly understand the naming. Ubuntu has 0.5.x and Red Hat 0.6.x - we'll make sure these are upgraded and let you know when this is automatically fixed.

**Comment by cpba** [comment]
Srain now shows up correctly on flathub.org:

https://flathub.org/apps/details/im.srain.Srain

I assume this has been fixed.
