### ISSUE TITLE
Srain 1.2.0 is built with meson

### ISSUE THREAD

**Issue by SilverRainZ** [flathub/im.srain.Srain#23]
@cpba How can we update Srain's mianfest to meson? I even can not found "./configure" in our mianfest file :'(

**Comment by cpba** [comment]
flatpak-builder has an option called `buildsystem`, you can pass `meson`
onto it and it'll take care of everything automatically. We weren't using
it already because autotools is the default setting.

Sorry to take so long, I haven't had a lot of time lately.
