### ISSUE TITLE
Update to 1.0.0rc1

### ISSUE THREAD

**Issue by SilverRainZ** [flathub/im.srain.Srain#5]
Hi @cpba, can you please update Srain to the newest master branch(a.k.a 1.0.0rc1)? The newst install guide can be found [here](http://doc.srain.im/en/latest/install.html).

**Comment by cpba** [comment]
@SilverRainZ I've opened pull request #7 that builds the latest commit from the master branch.

I've dropped the python modules and imagemagick as they don't seem to be used any longer.

After some light testing I've seen a couple things that could be bugs, the "image envelope" icon in the lower right corner is missing and the links in the #srain channel topic display an "unsupported content type" message.

I'm attaching a screenshot for clarity:

![srain1](https://user-images.githubusercontent.com/11727844/47270560-cbac0500-d56d-11e8-86d8-a746be9fccca.png)

**Comment by SilverRainZ** [comment]
> I've dropped the python modules and imagemagick as they don't seem to be used any longer.

OK, both of them are no longer needed.

> After some light testing I've seen a couple things that could be bugs, the "image envelope" icon in the lower right corner is missing.

This icon is replaced by the "dialog-ok" icon and which seems do not exist in adwaita icon theme, it is hard to find a appropriate in default icon theme :'(, just leave it here for now.

> the links in the #srain channel topic display an "unsupported content type" message.

This is the new URL preview feature, currently it will preview all URLs in the message and topic, even if the URL is unable to be previewed. I will fix this problem ASAP.

**Comment by TingPing** [comment]
> This icon is replaced by the "dialog-ok" icon and which seems do not exist in adwaita icon theme, it is hard to find a appropriate in default icon theme :'(, just leave it here for now.

Just bundle it in gresources.

**Comment by SilverRainZ** [comment]
@cpba This 2 issues should be fixed, please try https://github.com/SilverRainZ/srain/commit/4dda1952669143c6366cb6954ca283a3095c6d22.

**Comment by cpba** [comment]
@SilverRainZ I have updated the pull request, you can merge it as soon as you are happy with it.

I may have found another bug with it regarding the send icon, I'll investigate and send you another pull request.
